06:40:03,566 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:40:03,566 __main__ INFO executing...
06:40:03,566 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:40:03,566 __main__ INFO executing...
06:40:03,566 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:40:03,566 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:40:03,566 __main__ INFO executing...
06:41:56,904 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:41:56,904 __main__ INFO executing...
06:41:56,904 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:41:56,904 __main__ INFO executing...
06:48:53,970 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:48:53,970 __main__ INFO executing...
06:48:53,971 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:48:53,971 __main__ INFO executing...
06:49:50,568 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:49:50,568 __main__ INFO executing...
06:49:50,569 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:49:50,569 __main__ INFO executing...
06:49:50,569 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:49:50,569 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:49:50,569 __main__ INFO executing...
06:50:05,707 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:50:05,707 __main__ INFO executing...
06:50:05,707 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:50:05,707 __main__ INFO executing...
06:50:05,708 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:50:05,708 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:50:05,708 __main__ INFO executing...
06:50:24,293 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:50:24,293 __main__ INFO executing...
06:50:24,293 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:50:24,293 __main__ INFO executing...
06:50:24,293 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:50:24,293 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:50:24,293 __main__ INFO executing...
06:50:33,948 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:50:33,948 __main__ INFO executing...
06:50:33,948 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:50:33,948 __main__ INFO executing...
06:50:33,949 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:50:33,949 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:50:33,949 __main__ INFO executing...
06:51:03,412 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:51:03,412 __main__ INFO executing...
06:51:03,412 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:51:03,412 __main__ INFO executing...
06:51:03,412 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:51:03,412 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:51:03,412 __main__ INFO executing...
06:51:23,666 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:51:23,666 __main__ INFO executing...
06:51:23,666 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:51:23,666 __main__ INFO executing...
06:51:23,666 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:51:23,666 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:51:23,666 __main__ INFO executing...
06:51:38,473 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:51:38,473 __main__ INFO executing...
06:51:38,473 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:51:38,473 __main__ INFO executing...
06:51:38,473 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:51:38,473 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:51:38,473 __main__ INFO executing...
06:52:03,520 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:52:03,520 __main__ INFO executing...
06:52:03,520 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:52:03,520 __main__ INFO executing...
06:52:03,521 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:52:03,521 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:52:03,521 __main__ INFO executing...
06:52:28,917 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:52:28,917 __main__ INFO executing...
06:52:28,917 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:52:28,917 __main__ INFO executing...
06:52:28,917 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:52:28,917 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:52:28,917 __main__ INFO executing...
06:53:14,974 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:53:14,974 __main__ INFO executing...
06:53:14,974 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:53:14,974 __main__ INFO executing...
06:55:33,553 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:55:33,554 __main__ INFO executing...
06:55:33,554 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:55:33,554 __main__ INFO executing...
06:55:33,554 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:55:33,554 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:55:33,554 __main__ INFO executing...
06:55:57,305 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:55:57,305 __main__ INFO executing...
06:55:57,305 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
06:55:57,305 __main__ INFO executing...
06:55:57,305 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 57, in <module>
    stdout_wrapper(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 29, in stdout_wrapper
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

06:55:57,305 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
06:55:57,305 __main__ INFO executing...
07:06:38,503 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:06:38,503 __main__ INFO executing...
07:07:06,94 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:07:06,94 __main__ INFO executing...
07:07:06,95 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
07:07:06,95 __main__ INFO executing...
07:07:06,95 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 25, in execute_request
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

07:07:06,95 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:07:06,95 __main__ INFO executing...
07:08:51,629 __main__ INFO import os, sys; os.chdir('/Volumes/GoogleDrive/.shortcut-targets-by-id/1FrvaCWSo3NV1g0sR9ib6frv_lzRww_8K/CycAI/works/CAT/machine_simulation'); sys.path.append(os.getcwd()); from libs.multidataframes import CycDataFrame; training_data = CycDataFrame('data/exp_data/997/21549286_out.csv')
07:09:20,358 __main__ INFO {'command_type': 'exec', 'command': "import os, sys; os.chdir('/Volumes/GoogleDrive/.shortcut-targets-by-id/1FrvaCWSo3NV1g0sR9ib6frv_lzRww_8K/CycAI/works/CAT/machine_simulation'); sys.path.append(os.getcwd()); from libs.multidataframes import CycDataFrame; training_data = CycDataFrame('data/exp_data/997/21549286_out.csv')"}
07:09:20,358 __main__ INFO executing...
07:09:20,792 h5py._conv DEBUG Creating converter from 7 to 5
07:09:20,792 h5py._conv DEBUG Creating converter from 5 to 7
07:09:20,792 h5py._conv DEBUG Creating converter from 7 to 5
07:09:20,792 h5py._conv DEBUG Creating converter from 5 to 7
07:09:20,841 __main__ INFO {'command_type': 'exec', 'command': 'df = training_data.df'}
07:09:20,841 __main__ INFO executing...
07:09:27,515 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello world!")'}
07:09:27,516 __main__ INFO evaluating...
07:09:27,517 __main__ INFO None
07:09:29,193 __main__ INFO {'command_type': 'eval', 'command': 'df.t'}
07:09:29,193 __main__ INFO evaluating...
07:11:21,791 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:11:21,791 __main__ INFO executing...
07:11:21,791 __main__ INFO {'command_type': 'exec', 'command': 'failed command'}
07:11:21,791 __main__ INFO executing...
07:11:21,791 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 25, in execute_request
    exec(req['command'], globals())
  File "<string>", line 1
    failed command
           ^
SyntaxError: invalid syntax

07:11:21,791 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:11:21,791 __main__ INFO executing...
07:11:21,791 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:11:21,791 __main__ INFO executing...
07:11:21,791 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello")'}
07:11:21,791 __main__ INFO executing...
07:13:42,280 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:13:42,280 __main__ INFO evaluating...
07:13:42,280 __main__ INFO None
07:13:42,280 __main__ INFO {'command_type': 'eval', 'command': 'failed command'}
07:13:42,280 __main__ INFO evaluating...
07:13:42,280 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 30, in execute_request
    res = eval(req['command'])
  File "<string>", line 1
    failed command
           ^
SyntaxError: unexpected EOF while parsing

07:13:42,280 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:13:42,280 __main__ INFO evaluating...
07:13:42,280 __main__ INFO None
07:13:42,280 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:13:42,280 __main__ INFO evaluating...
07:13:42,281 __main__ INFO None
07:13:42,281 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:13:42,281 __main__ INFO evaluating...
07:13:42,281 __main__ INFO None
07:14:46,464 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello world!")'}
07:14:46,466 __main__ INFO evaluating...
07:14:46,467 __main__ INFO None
07:14:59,880 __main__ INFO {'command_type': 'eval', 'command': 'df.t'}
07:14:59,881 __main__ INFO evaluating...
07:16:08,109 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:16:08,109 __main__ INFO evaluating...
07:16:08,109 __main__ INFO None
07:16:08,109 __main__ INFO {'command_type': 'eval', 'command': 'failed command'}
07:16:08,109 __main__ INFO evaluating...
07:16:08,109 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 30, in execute_request
    res = eval(req['command'])
  File "<string>", line 1
    failed command
           ^
SyntaxError: unexpected EOF while parsing

07:16:08,109 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:16:08,109 __main__ INFO evaluating...
07:16:08,109 __main__ INFO None
07:16:08,109 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:16:08,109 __main__ INFO evaluating...
07:16:08,109 __main__ INFO None
07:16:08,109 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello")'}
07:16:08,109 __main__ INFO evaluating...
07:16:08,109 __main__ INFO None
07:16:17,192 __main__ INFO {'command_type': 'eval', 'command': 'df.t'}
07:16:17,194 __main__ INFO evaluating...
07:16:17,194 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 30, in execute_request
    res = eval(req['command'])
  File "<string>", line 1, in <module>
NameError: name 'df' is not defined

07:16:24,47 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello world!")'}
07:16:24,48 __main__ INFO evaluating...
07:16:24,49 __main__ INFO None
07:16:59,868 __main__ INFO {'command_type': 'exec', 'command': "import os, sys; os.chdir('/Volumes/GoogleDrive/.shortcut-targets-by-id/1FrvaCWSo3NV1g0sR9ib6frv_lzRww_8K/CycAI/works/CAT/machine_simulation'); sys.path.append(os.getcwd()); from libs.multidataframes import CycDataFrame; training_data = CycDataFrame('data/exp_data/997/21549286_out.csv')"}
07:16:59,868 __main__ INFO executing...
07:17:00,314 h5py._conv DEBUG Creating converter from 7 to 5
07:17:00,314 h5py._conv DEBUG Creating converter from 5 to 7
07:17:00,314 h5py._conv DEBUG Creating converter from 7 to 5
07:17:00,314 h5py._conv DEBUG Creating converter from 5 to 7
07:17:00,363 __main__ INFO {'command_type': 'exec', 'command': 'df = training_data.df'}
07:17:00,363 __main__ INFO executing...
07:17:03,544 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello world!")'}
07:17:03,545 __main__ INFO evaluating...
07:17:03,545 __main__ INFO None
07:17:05,353 __main__ INFO {'command_type': 'eval', 'command': 'df.t'}
07:17:05,354 __main__ INFO evaluating...
07:17:05,361 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 30, in execute_request
    res = eval(req['command'])
  File "<string>", line 1, in <module>
  File "/Users/bachbui/miniforge3/envs/py39a/lib/python3.9/site-packages/pandas/core/generic.py", line 5139, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 't'

07:17:07,651 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello world!")'}
07:17:07,651 __main__ INFO evaluating...
07:17:07,651 __main__ INFO None
07:17:09,529 __main__ INFO {'command_type': 'eval', 'command': 'df.describe()'}
07:17:09,530 __main__ INFO evaluating...
07:17:09,567 __main__ INFO        Fuel Rail Pressure  ...  Intake Manifold #2 Air Temperature
count         3599.000000  ...                         3599.000000
mean        133424.006669  ...                           29.365157
std          42152.568934  ...                            5.515255
min          65000.000000  ...                           22.800000
25%          71000.000000  ...                           25.200000
50%         153000.000000  ...                           27.000000
75%         166000.000000  ...                           32.400000
max         198000.000000  ...                           45.800000

[8 rows x 9 columns]
07:17:14,106 __main__ INFO {'command_type': 'eval', 'command': 'df[:30]'}
07:17:14,107 __main__ INFO evaluating...
07:17:14,108 __main__ INFO                             Fuel Rail Pressure  ...  Intake Manifold #2 Air Temperature
Global Time                                     ...                                    
2021-06-17 23:47:58.000000             70000.0  ...                                27.3
2021-06-17 23:47:59.000001             70000.0  ...                                27.3
2021-06-17 23:48:00.000000             69000.0  ...                                27.3
2021-06-17 23:48:01.000000             72000.0  ...                                27.3
2021-06-17 23:48:01.999999             71000.0  ...                                27.3
2021-06-17 23:48:03.000000             76000.0  ...                                27.3
2021-06-17 23:48:04.000000            125000.0  ...                                27.3
2021-06-17 23:48:04.999999            129000.0  ...                                27.3
2021-06-17 23:48:06.000000            122000.0  ...                                27.2
2021-06-17 23:48:07.000000             97000.0  ...                                27.2
2021-06-17 23:48:08.000000             72000.0  ...                                27.2
2021-06-17 23:48:09.000000             71000.0  ...                                27.1
2021-06-17 23:48:10.000000            116000.0  ...                                27.1
2021-06-17 23:48:11.000000            145000.0  ...                                27.1
2021-06-17 23:48:12.000000            174000.0  ...                                27.1
2021-06-17 23:48:13.000000            132000.0  ...                                27.0
2021-06-17 23:48:14.000000            137000.0  ...                                27.0
2021-06-17 23:48:15.000001            122000.0  ...                                26.9
2021-06-17 23:48:16.000000            128000.0  ...                                26.8
2021-06-17 23:48:17.000000            137000.0  ...                                26.8
2021-06-17 23:48:18.000001            188000.0  ...                                26.7
2021-06-17 23:48:19.000000            140000.0  ...                                26.6
2021-06-17 23:48:20.000000            157000.0  ...                                26.5
2021-06-17 23:48:20.999999            153000.0  ...                                26.3
2021-06-17 23:48:22.000000            149000.0  ...                                26.2
2021-06-17 23:48:23.000000            140000.0  ...                                26.1
2021-06-17 23:48:23.999999            130000.0  ...                                25.9
2021-06-17 23:48:25.000000            122000.0  ...                                25.9
2021-06-17 23:48:26.000000            104000.0  ...                                25.8
2021-06-17 23:48:27.000000            166000.0  ...                                25.8

[30 rows x 9 columns]
15:30:40,339 __main__ INFO {'command_type': 'eval', 'command': 'import pandas as pd'}
15:30:40,349 __main__ INFO evaluating...
15:30:40,361 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 30, in execute_request
    res = eval(req['command'])
  File "<string>", line 1
    import pandas as pd
    ^
SyntaxError: invalid syntax

15:32:57,630 __main__ INFO {'command_type': 'eval', 'command': 'print("Hello world!")'}
15:32:57,636 __main__ INFO evaluating...
15:32:57,643 __main__ INFO None
15:33:09,143 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello world!")'}
15:33:09,144 __main__ INFO executing...
15:33:19,983 __main__ INFO {'command_type': 'exec', 'command': 'import pandas as pd'}
15:33:19,984 __main__ INFO executing...
19:20:09,292 __main__ INFO {'command_type': 'exec', 'command': 'df[:10]'}
19:20:09,296 __main__ INFO executing...
19:20:26,184 __main__ INFO {'command_type': 'exec', 'command': 'dfs'}
19:20:26,185 __main__ INFO executing...
19:20:26,186 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 25, in execute_request
    exec(req['command'], globals())
  File "<string>", line 1, in <module>
NameError: name 'dfs' is not defined

19:20:57,299 __main__ INFO {'command_type': 'exec', 'command': 'dfs'}
19:20:57,300 __main__ INFO executing...
19:20:57,301 __main__ ERROR Traceback (most recent call last):
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 58, in <module>
    result = execute_request(req)
  File "/Users/bachbui/works/auto_task/frontend_apps/cycdataframe/server/server.py", line 25, in execute_request
    exec(req['command'], globals())
  File "<string>", line 1, in <module>
NameError: name 'dfs' is not defined

20:13:05,28 __main__ INFO {'command_type': 'exec', 'command': 'df[:5]'}
20:13:05,30 __main__ INFO executing...
20:13:17,778 __main__ INFO {'command_type': 'exec', 'command': 'print(df[:5])'}
20:13:17,778 __main__ INFO executing...
20:20:48,405 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello world!")'}
20:20:48,407 __main__ INFO executing...
20:20:53,261 __main__ INFO {'command_type': 'exec', 'command': 'print("Hello world!")'}
20:20:53,261 __main__ INFO executing...
12:19:37,270 __main__ INFO {'command_type': 'exec', 'command': "import os, sys; os.chdir('/Volumes/GoogleDrive/.shortcut-targets-by-id/1FrvaCWSo3NV1g0sR9ib6frv_lzRww_8K/CycAI/works/CAT/machine_simulation'); sys.path.append(os.getcwd()); from libs.multidataframes import CycDataFrame; training_data = CycDataFrame('data/exp_data/997/21549286_out.csv')"}
12:19:37,270 __main__ INFO executing...
12:19:37,878 h5py._conv DEBUG Creating converter from 7 to 5
12:19:37,878 h5py._conv DEBUG Creating converter from 5 to 7
12:19:37,878 h5py._conv DEBUG Creating converter from 7 to 5
12:19:37,878 h5py._conv DEBUG Creating converter from 5 to 7
12:19:37,950 __main__ INFO {'command_type': 'exec', 'command': 'df = training_data.df'}
12:19:37,950 __main__ INFO executing...
12:30:18,969 __main__ INFO {'command_type': 'exec', 'command': "import os, sys; os.chdir('/Volumes/GoogleDrive/.shortcut-targets-by-id/1FrvaCWSo3NV1g0sR9ib6frv_lzRww_8K/CycAI/works/CAT/machine_simulation'); sys.path.append(os.getcwd()); from libs.multidataframes import CycDataFrame; training_data = CycDataFrame('data/exp_data/997/21549286_out.csv')"}
12:30:18,969 __main__ INFO executing...
12:30:19,413 h5py._conv DEBUG Creating converter from 7 to 5
12:30:19,413 h5py._conv DEBUG Creating converter from 5 to 7
12:30:19,413 h5py._conv DEBUG Creating converter from 7 to 5
12:30:19,413 h5py._conv DEBUG Creating converter from 5 to 7
12:30:19,466 __main__ INFO {'command_type': 'exec', 'command': 'df = training_data.df'}
12:30:19,466 __main__ INFO executing...
16:31:41,58 __main__ INFO {'command_type': 'exec', 'command': "import os, sys; os.chdir('/Volumes/GoogleDrive/.shortcut-targets-by-id/1FrvaCWSo3NV1g0sR9ib6frv_lzRww_8K/CycAI/works/CAT/machine_simulation'); sys.path.append(os.getcwd()); from libs.multidataframes import CycDataFrame; training_data = CycDataFrame('data/exp_data/997/21549286_out.csv')"}
16:31:41,58 __main__ INFO executing...
16:31:41,639 h5py._conv DEBUG Creating converter from 7 to 5
16:31:41,639 h5py._conv DEBUG Creating converter from 5 to 7
16:31:41,639 h5py._conv DEBUG Creating converter from 7 to 5
16:31:41,640 h5py._conv DEBUG Creating converter from 5 to 7
16:31:41,710 __main__ INFO {'command_type': 'exec', 'command': 'df = training_data.df'}
16:31:41,710 __main__ INFO executing...
